In [3]:
#1
import numpy as np
a = np.array([10,20,30,40,50])
print(a)
print(type(a))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
#2
b = np.array(([1,2],[3,4],[4,5]))
print(b)

[[1 2]
 [3 4]
 [4 5]]


In [12]:
#3
c = np.array([7,8,9],dtype = float)
print(c)
print(type(c))

[7. 8. 9.]
<class 'numpy.ndarray'>


In [18]:
#4
print(np.zeros(6))
print(np.ones((3,2),dtype = int))

[0. 0. 0. 0. 0. 0.]
[[1 1]
 [1 1]
 [1 1]]


In [21]:
#5
print(np.empty((2,3)))

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [24]:
#6
print(np.arange(0,20,2))

print(np.linspace(0,1,6))

#The difference betweeen arange() and linspace() is that in arange() the ending value is exclusive and in linspace() the ending value is inclusive

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1. ]


In [27]:
#7
print(np.random.random((3,3)))

[[0.57561275 0.72388599 0.60358641]
 [0.94811599 0.29562913 0.91619264]
 [0.91693919 0.74411355 0.4341103 ]]
