In [1]:
#1
import numpy as np
arr = np.arange(21)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(21,)
21
int64


In [30]:
#2
np.random.seed(0)
array = np.random.randint(50,size=(4,5))
print(array)
array.nbytes
array.itemsize

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]


4

In [27]:
#3
arr = np.arange(1,13).reshape(3,4)
print(arr)

print(arr[1])
print(arr[:,2])

print(arr[-1,:])

print(arr[:,-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 3  7 11]
[ 9 10 11 12]
[ 4  8 12]
