In [26]:
#1

import numpy as np
np.random.seed(1)
x = np.random.randint(1,100,10)
print(x)
np.sort(x)

[38 13 73 10 76  6 80 65 17  2]


In [32]:
#2

s = np.array([38,13,73,10,76,6,80,65,17,2])
i = np.argsort(x)
print(i)


[0 1 2 3 4 5 6 7 8 9]


In [86]:
#3

import random
x=np.random.randint(1,100,(4,6))
print("Random array : \n",x)

arr1 = np.sort(x,axis=1)
print("Row wise sorted array :  \n",arr1)

arr2 =  np.sort(x,axis=0)
print("Columnm wise sorted array: \n",arr2)

Random array : 
 [[20 13 26 78 17  5]
 [89 28 51 69  4 59]
 [13  3 77 97 97 62]
 [16 75 13 19 31 60]]
Row wise sorted array :  
 [[ 5 13 17 20 26 78]
 [ 4 28 51 59 69 89]
 [ 3 13 62 77 97 97]
 [13 16 19 31 60 75]]
Columnm wise sorted array: 
 [[13  3 13 19  4  5]
 [16 13 26 69 17 59]
 [20 28 51 78 31 60]
 [89 75 77 97 97 62]]


In [115]:
#4

array = np.random.randint(1,15,15)
print(array)
array1 = np.partition(array,4)
print(array1)
np.sort(array)

[ 1 10 14  4  2  9  1 14  5  8 12  3  4  1  1]
[ 1  1  1  1  2  3  4  4  5  8  9 10 12 14 14]


array([ 1,  1,  1,  1,  2,  3,  4,  4,  5,  8,  9, 10, 12, 14, 14],
      dtype=int32)

In [122]:
#5

import numpy as np

student_names = np.array(["Anish", "Haneesh", "Basanth", "Vishwa"])
scores = np.array([88, 72, 95, 64])

index = np.argsort(scores)

ranked_students = student_names[index]

print(ranked_students)

array([3, 1, 0, 2])