In [1]:
import numpy as np

a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))

print(a)
print(b)

vertical1 = np.vstack((a, b))
vertical2 = np.concatenate((a, b), axis=0)

print(vertical1)
print(vertical2)

print(np.array_equal(vertical1, vertical2))



[[6 7 6]
 [3 8 5]]
[[2 6 3]
 [3 3 1]]
[[6 7 6]
 [3 8 5]
 [2 6 3]
 [3 3 1]]
[[6 7 6]
 [3 8 5]
 [2 6 3]
 [3 3 1]]
True


In [7]:
horizontal1 = np.hstack((a, b))
horizontal2 = np.concatenate((a, b), axis=1)

print(horizontal1)
print(horizontal2)

print(np.array_equal(horizontal1, horizontal2))

[[6 7 6 2 6 3]
 [3 8 5 3 3 1]]
[[6 7 6 2 6 3]
 [3 8 5 3 3 1]]
True


In [8]:
import numpy as np
x = np.arange(1, 16)

print(x)

parts = np.split(x, 3)

print(parts[0])
print(parts[1])
print(parts[2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [9]:
import numpy as np

x = np.random.randint(1, 100, 15)
print(x)
p = np.partition(x, 4)

print(p[:4])
s = np.sort(x)

print(s[:4])

[46 34 42 13 30 60 51 55 59 30  7 62 71 70 91]
[ 7 13 30 30]
[ 7 13 30 30]


In [10]:
import numpy as np

x = np.arange(1, 25).reshape(6, 4)
print(x)
horizontal = np.hsplit(x, 2)

print(horizontal[0])
print(horizontal[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]


In [6]:
vertical = np.vsplit(x, 2)
print(vertical[0])
print(vertical[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
